#include<stdio.h>

int main()
{

printf("------------PARA NO.08---------------:\n");
printf("8:(111):And if We had sent down angels towards them, and had the dead spoken to them, and had We brought all things in front of them, even then they were not to believe unless Allah willed; but most of them are totally ignorant.\n");
printf("8:(112):And We have appointed enemies in a like manner for every Prophet; devils from men and Jinn, that one whispers secretly to the other with fabrications in order to deceive. And had your Lord willed, they would not have hence done so; leave them therefore on their fabrications.\n");
printf("8:(113):And for this reason; that the hearts of those who do not believe in the Hereafter may be inclined towards it (i.e. the fabrications), and that they may like it, and earn the sins which they (the devils) are to earn.\n");
printf("8:(114):'So, should I seek the judgement of someone other than Allah, and it is only He Who has sent down the Book towards you in detail?' And to those whom We gave the Book know that this is sent down from your Lord with the truth. So, O listener! You must never be of those who doubt.\n");
printf("8:(115):And the Word of your Lord is complete in truth and justice; there is no one to change His Words. And only He is the All-Hearing, the All-Knowing.\n");
printf("8:(116):And O listener! Most of the people on earth are such that (if) you were to obey their sayings, they would therefore mislead you from the way of Allah; they follow assumptions only and they make mere speculations.\n");
printf("8:(117):Your Lord knows well who has gone astray from His way, and He (also) knows well the guided ones.\n");
printf("8:(118):So, eat from that upon which the Name of Allah has been mentioned (at the time of slaughtering), if you believe in His verses.\n");
printf("8:(119):And what has happened to you; that you should not eat from that upon which the Name of Allah has been mentioned (at the time of slaughtering)? He has already explained in detail to you whatever has been made unlawful to you except when you are compelled towards it. And verily, many mislead (other people) by their own desires; out of ignorance. Indeed, your Lord knows well the transgressors.\n");
printf("8:(120):And give up open and hidden sins; those who earn sins will soon receive the punishment of their earnings.\n");
printf("8:(121):And do not eat that upon which Allah's Name has not been mentioned (at the time of slaughtering) and (eating) that is indeed disobedience. And the devils undoubtedly whisper in the hearts of their friends that they fight with you; and if you obey them, so, at that time, you are (also) polytheists.\n");
printf("8:(122):And will the one who was dead; so, We raised him to life and set for him a light with which he walks amongst the people, ever be like that one who is in darknesses which he is never to come out from? Likewise, the deeds of the disbelievers are made to appear good in their eyes.\n");
printf("8:(123):And similarly, in every town, We have made the leaders of its criminals that they may devise a plot in it; and they do not plot except against themselves and (yet) they perceive not.\n");
printf("8:(124):And when any sign comes to them, they say, 'We will never believe until we are given similar to what the Messengers of Allah were given.' Allah knows best where to place His Messengership (i.e. to whom it should be given). Soon, the criminals will be afflicted with disgrace before Allah and a severe punishment; the recompense of their deceitfulness.\n");
printf("8:(125):And whomsoever Allah wills to guide, He opens his chest for Islam; and whomever He wills to become astray, He makes his chest narrow and extremely constrained as if he was being forced by someone to climb the sky; this is how Allah inflicts punishment on those who do not believe.\n");
printf("8:(126):And this (i.e. the Shari'ah of Islam) is the straight path of your Lord, We have explained in detail Our verses for the people who accept advice.\n");
printf("8:(127):For them is the home of peace with their Lord and He is their Master; this is the result of their (good) deeds.\n");
printf("8:(128):And (remember) the Day when He will raise all of them (from their graves) and will proclaim, 'O you group of (evil) Jinn! You have encircled a lot of humans (in your evils),' and their human friends will submit, 'O our Lord! We have benefited from one another and have reached the appointed term which You had set for us.' He (Allah) will say, 'Your abode is the Fire; (you will) remain therein forever except whomsoever Allah wills.' O Beloved, your Lord is indeed All-Wise, All-Knowing.\n");
printf("8:(129):And likewise, We enable some of the oppressors to overpower other (oppressors); the recompense of their actions.\n");
printf("8:(130):'O groups of Jinn and humans! Did the Messengers from amongst you not come to you, reciting upon you My verses and warning you of seeing this Day?' They will say, 'We testified against ourselves.' And the worldly life deceived them and they themselves will testify against their souls that they were disbelievers.\n");
printf("8:(131):This (sending of Prophets) is because your Lord does not unjustly destroy towns whilst the people of those towns remain unaware.\n");
printf("8:(132):And for everyone there are different degrees of their (good or bad) deeds; and your Lord is not unaware of their deeds.\n");
printf("8:(133):And O Beloved, your Lord is the Independent, the Merciful. O people! If He wills, He may take you away and bring in your place whomsoever He wills, just like He created you from the descendants of others.\n");
printf("8:(134):Indeed, that which you are promised is definitely to come, and you cannot make (Allah) tired.\n");
printf("8:(135):Say you (O Beloved), 'O my people! You continue working according to your position (of evilness), I am working according to mine (of goodness); so, you are now going to know for whom is (and is not) the (better) abode of the Hereafter. Undoubtedly, the unjust do not attain success.\n");
printf("8:(136):And amongst the crops and animals which Allah has created, they (i.e. polytheists) fixed one share for Allah; they therefore said according to their perception, 'This is for Allah, and this is for our partners (i.e. false deities).' Thus, that (share) which is for their partners does not reach Allah, and that (share) which is for Allah; that reaches their partners; what an evil decision they make.\n");
printf("8:(137):And similarly, their partners (i.e. the devils) have made the killing of children seem noble in the sight of many of the polytheists, in order to ruin them and cause confusion in their religion. And had Allah willed, they would not have hence done so; therefore, leave them and their fabrications alone.\n");
printf("8:(138):And according to their false presumption, they said, 'These cattle and crops are forbidden (to take benefit from); only those may eat whom we desire.' And some cattle are those upon which is made unlawful (by them) to ride upon. And there are some cattle upon which they do not mention the Name of Allah whilst slaughtering. All this is fabricating lie against Allah, He will soon recompense them of their fabrications.\n");
printf("8:(139):And they said, 'Those (animals) in the bellies of such cattle are purely for our men and unlawful upon our women; and if (the animal) is stillborn, they all therefore have a share of it.' It is near that Allah will recompense them for their (baseless) matters; indeed, He is All-Wise, All-Knowing.\n");
printf("8:(140):Indeed, ruined are those who kill their children out of senseless ignorance and regard unlawful that which Allah has provided for them (by making some animals sacred) for the purpose of fabricating lie against Allah; they have undoubtedly gone astray and did not attain the (right) path.\n");
printf("8:(141):And it is He Who caused gardens to be produced; some spread out on the ground and some not spread out, and the date palm and crops in which are various kinds of foods, and the olive and the pomegranate; similar in some respects and unlike in others; eat its fruit when it bears fruits, and pay the due ('Ushr) from it on the day it is harvested, and do not spend wastefully; indeed, He does not like the wasteful.\n");
printf("8:(142):And from the cattle, (there are) some for carrying burden (e.g. camels, etc.) and some spread on the earth (not carrying weight); eat from that which Allah has sustained you with, and do not follow the footsteps of the Devil; undoubtedly, he is your open enemy.\n");
printf("8:(143):'(Allah created) eight males and females; one pair of sheep and one pair of goats.' Say you (O Beloved), 'Has He forbidden both males or both females, or what the two females are carrying in their wombs? Respond with any (certain) knowledge, if you are truthful.\n");
printf("8:(144):'And (Allah created) a pair of camels and a pair of cows.' Say you (O Beloved), 'Has He forbidden the two males or the two females, or what the two females are carrying in their wombs? Were you present when Allah commanded this to you?' So, who is more unjust than the one who fabricates lie against Allah in order to lead people astray due to his ignorance? Indeed, Allah does not guide the unjust (due to their persistence upon disbelief).\n");
printf("8:(145):Say you (O Beloved), 'I do not find within that which has been revealed to me any food unlawful for the one who eats except if it is carrion (i.e. dead meat), or blood flowing out of the veins, or the flesh of swine; that it is impurity, or an animal (becoming a cause) of disobedience over which the name of other than Allah is mentioned at the time of slaughtering; (except) for the one therefore compelled (by necessity due to a life-threatening state of hunger), neither desiring it himself, nor exceeding the need. So, your Lord indeed is Most Forgiving, Ever Merciful.\n");
printf("8:(146):And for the Jews, We forbade every animal with claws and forbade them the fat of cow and sheep except (the fat) which is on their (animal's) backs, or attached to their intestines or to the bone; We penalised them for their rebellion, and We are indeed definitely Truthful.\n");
printf("8:(147):If they then belie you (O Beloved); so, you say, 'Your Lord is the Possessor of Vast Mercy, and His punishment is not averted from the culprits.\n");
printf("8:(148):The polytheists will now say that 'Had Allah desired, we would not have associated partners (to Him) nor would have our forefathers, nor would we have regarded anything as unlawful.' Similarly, those before them had belied, until they tasted Our punishment. Say you (O Beloved), 'Do you have any knowledge that you produce for Us? You follow only assumptions and only speculate.\n");
printf("8:(149):The polytheists will now say that 'Had Allah desired, we would not have associated partners (to Him) nor would have our forefathers, nor would we have regarded anything as unlawful.' Similarly, those before them had belied, until they tasted Our punishment. Say you (O Beloved), 'Do you have any knowledge that you produce for Us? You follow only assumptions and only speculate.\n");
printf("8:(150):Say you (O Beloved), 'Bring those witnesses of yours who testify that Allah has forbidden this (i.e. the things which you regard as unlawful),' if they do then testify, so, O listener! Do not bear witness with them, and do not follow the desires of those who belie Our verses, and those who do not believe in the Hereafter and who ascribe an equal to their Lord.\n");
printf("8:(151):Say you (O Beloved), 'Come, so that I may recite to you what your Lord has made unlawful for you; this; that 'Do not ascribe any partner to Him, and be good to parents, and do not kill your children because of poverty; We shall provide sustenance for all; you and them, and do not approach indecent acts; (those) which are open amongst them and (those) which are concealed, and do not unjustly kill any life which Allah has made sacred; He has ordered you this, so that you may understand.\n");
printf("8:(152):'And do not approach the wealth of orphans except in the best manner, until he reaches maturity; and measure and weigh in full, with justice. We do not burden any soul except according to its capacity, and when you speak; so, speak justly, although it may be a matter concerning your own relative. And fulfil your covenant with Allah; (He has) emphasised this to you, that somehow you accept advice.\n");
printf("8:(153):'And (know) that This (i.e. the Islamic Shari'ah) is My straight path; therefore, follow it, and do not follow other ways; that they will separate you from His Way; He commanded this to you, that you may attain piety.\n");
printf("8:(154):We then gave the Book to Moosa to complete the favour on the one who is virtuous, and (it) is an explanation of everything, guidance and mercy; that they may believe in meeting their Lord.\n");
printf("8:(155):And this (i.e. the Qur'aan) is a Blessed Book which We have revealed; therefore, follow it and practise piety, that you may attain mercy.\n");
printf("8:(156):(The Qur'aan is revealed for the reason that) lest you should say that 'The Book was sent down only to two groups (i.e. the Jews and the Christians) before us, and we were totally unaware of their readings and teachings.\n");
printf("8:(157):Or you may say that 'If the Book had been sent down to us, we would have therefore been upon guidance more than them.' So, the clear proof, and guidance and mercy has come to you from your Lord; therefore, who is more unjust than the one who belies the verses of Allah and turns his face away from them? We shall soon punish those who turn away their faces from Our verses with a brutal punishment; the recompense for the turning away of their faces.\n");
printf("8:(158):What are they waiting for except that angels come to them, or the punishment of your Lord comes or a sign of your Lord comes? On the Day (of Judgement), when a sign of your Lord will come, no soul will benefit from accepting faith (at that time) which had not earlier accepted faith nor earned any good from its faith. Say you (O Beloved), 'Wait; we are also waiting.\n");
printf("8:(159):Those who made separate paths in their religion and became several groups, O Beloved, you have no connection with them; their matter is only with Allah, He will then inform them of what they used to do.\n");
printf("8:(160):Whosoever brings one good deed, for him there are therefore ten like it; and the one who brings an evil deed, he will therefore not be recompensed but to its equal; and they will not be wronged.\n");
printf("8:(161):Say you (O Beloved), 'Indeed, my Lord has shown me the Straight Path; the right religion; the religion of Ibrahim who was detached from every falsehood and was not a polytheist.\n");
printf("8:(162):Say you (O Beloved), 'My Salah, and my sacrifices, and my living and my passing away are all undoubtedly for Allah Who is the Lord of all the worlds.\n");
printf("8:(163):He has no partner; this is what I have been commanded, and I (the Prophet Muhammad) am the first Muslim (in terms of being the first of creation).\n");
printf("8:(164):He has no partner; this is what I have been commanded, and I (the Prophet Muhammad) am the first Muslim (in terms of being the first of creation).\n");
printf("8:surah-last(165):And it is He Who made you vicegerents on earth and (O people! He) has raised one over the other in ranks amongst you, in order that He may test you with what He has bestowed upon you. Verily, it does not take time for your Lord to punish, and He is indeed definitely Most Forgiving, Ever Merciful.\n");

printf("8:SURAH AL-AARAAF\nTOTAL RUKU(24)\nTOTAL AYAAT(206)\nTOTAL WORD(3707)\n TOTAL LETTER(14207)\nTARTEEB NUZOOL(39)\n");

printf("Allah's Name to commence with, the Most Gracious, the Most Merciful.");
printf("8:(1):Alif-Laam-Meem-Saad. (These are individual letters of the Arabic alphabet; Allah and His Messenger know their exact meanings.)\n");
printf("8:(2):O Beloved! A Book has been sent to you; so, let not your heart become discouraged towards it (thinking that people will not accept), so that you may give warning therewith and advice to the Muslims.\n");
printf("8:(3):O people! Follow what has come down to you from your Lord, and do not follow rulers abandoning it (i.e. the commandments of the Qur'aan); there is very little you understand.\n");
printf("8:(4):And many a town We have destroyed; so, Our punishment came to them at night or while they were sleeping at noon.\n");
printf("8:(5):Therefore, nothing came out from their mouths when Our punishment came upon them except they said only this; that 'We were unjust.\n");
printf("8:(6):So, We shall indeed definitely question those to whom Messengers went, and We are to indeed certainly ask the Messengers (as well).\n");
printf("8:(7):So, We shall definitely inform them with Our knowledge and We were not at all absent.\n");
printf("8:(8):And on that Day, weighing is to certainly take place; those whose scales became heavy are therefore the successful.\n");
printf("8:(9):And those whose scales became light are only those who put their souls at loss; the recompense of those injustices which they used to do with Our verses.\n");
printf("8:(10):And We indeed established you on earth and therein created for you the means of livelihood; very little thanks do you offer.\n");
printf("8:(11):And We indeed created you, then made your forms, then ordered the angels that 'Prostrate to Adam,' they all therefore prostrated except Iblees (Satan); he did not become of those who prostrate.\n");
printf("8:(12):(Allah) said, 'What prevented you that you did not prostrate when I commanded you?' Answered he (Iblees), 'I am better than him; You created me from fire and created him from clay.\n");
printf("8:(13):Said (Allah), 'So, get down from here (Paradise)! It does not befit you to stay here, being arrogant; get out! You are of the degraded ones!\n");
printf("8:(14):He (Satan) said, 'Give me respite till the Day that people are resurrected.\n");
printf("8:(15):Said (Allah), 'You are given respite.\n");
printf("8:(16):He (Satan) said, 'Hence, I swear by the fact that You led me astray (although, in reality him going astray was down to his own doing), I will certainly lurk in ambush for them (i.e. the children of Adam) on Your straight path.\n");
printf("8:(17):I will then certainly come to them; from in front of them, and from the back, and from the right, and from the left; and you will find most of them ungrateful.\n");
printf("8:(18):He (Allah) said, 'Get out from here; rejected, banished (with disgrace)! Whoever amongst them follows your call, I will definitely fill Hell with all of you.\n");
printf("8:(19):And O Adam, you and your wife dwell in Paradise; so, eat from it from wherever you desire. And do not approach this tree; that you would be amongst those who exceed the limit.\n");
printf("8:(20):The Devil then whispered into their hearts in order to disclose their (body) parts of shame to them, which were (previously) hidden from them, and said, 'Your Lord has forbidden you from this tree; that you may not become angels or live forever.\n");
printf("8:(21):And he swore an oath to them that 'I am indeed a well-wisher for both of you.\n");
printf("8:(22):So, he brought them down by deception (by swearing an oath using the Name of Allah). Then when they tasted (the fruit of) that tree, the areas of their shame became manifest to them and they began affixing the leaves of Paradise upon their bodies. And their Lord said to them, 'Did I not forbid you from that tree and not tell you that the Devil is your open enemy?\n");
printf("8:(23):They both submitted, 'O our Lord, we have wronged ourselves; so, if You do not forgive us and do not have mercy upon us, we hence certainly became amongst those in loss.\n");
printf("8:(24):He (Allah) said, 'Go down you (i.e. Adam, Hawwa, as well as the progeny of Adam in his loin) as enemies of one another, and you are to stay on earth for a fixed time and benefit therefrom.\n");
printf("8:(25):He (Allah) said, 'There you shall live and there you shall die, and from there you will be raised.\n");
printf("8:(26):O descendants of Adam! Undoubtedly, We have sent down to you a garment that may conceal your parts of shame, and another for your adornment; the garment of piety (faith and good character); that is the best; this is among the signs of Allah that they may accept advice.\n");
printf("8:(27):O descendants of Adam, beware! Let not the Devil put you in trial the way he removed your parents from Paradise and had their garments removed so that the things of their shame became visible to them; indeed, he and his tribe see you from where you see them not. Indeed, We have made devils the friends of those who do not believe.\n");
printf("8:(28):And when they (the polytheists) commit a shameful act, they hence say, 'We found our forefathers upon it and Allah has commanded it to us.' Say you (O Beloved), 'Indeed, Allah does not command shamelessness; do you attribute things to Allah, which you know not?\n");
printf("8:(29):Say you (O Beloved), 'My Lord has commanded justice. And set your face straight every time you offer Salah and worship solely Him, being His devoted bondsmen; the way He originated you; you will return in the same manner.\n");
printf("8:(30):He guided one group, and the misguidance of one group was proven; instead of Allah, they made devils their friends and they assume this; that they are on guidance.\n");
printf("8:(31):O children of Adam! Adorn yourself when you go to the Masjid, and eat and drink, and do not cross the limit; indeed, He does not like those who cross the limit (i.e. the extravagant).\n");
printf("8:(32):Say you (O Beloved), 'Who has made unlawful the adornment of Allah which He has brought forth for His bondsmen, and pure sustenance?' Say you; that 'It is for the believers in this world and on the Day of Resurrection; so, it will solely be for them,' this is how We explain the verses in detail for the people of knowledge.\n");
printf("8:(33):Say you (O Beloved), 'My Lord has made indecencies unlawful; those which are open and those which are hidden, and sin and wrongful oppression, and this; that you associate as partners with Allah for which He has not sent down any authority, and this; that you say those things concerning Allah of which you have no knowledge.\n");
printf("8:(34):And for every group there is a promise (of fixed time); so, when their promise (of death) will come, it will not delay (even) a moment nor advance.\n");
printf("8:(35):O children of Adam! If Messengers from amongst you come to you reciting My verses, whosoever therefore adopts piety and reforms (himself); so, upon him is no fear nor any grief\n");
printf("8:(36):And those who belied Our verses and became arrogant against them, they are the people of Hell, wherein they will remain forever.\n");
printf("8:(37):So, who is more unjust than the one who fabricated lie against Allah or belied His verses? Their written fate will reach them, until Our sent ones (i.e. the angels) come to remove their souls; so, they (the angels) say to them, 'Where are those whom you used to worship other than Allah?' (In reply) they say, 'We have lost them.' And they bear witness against their own souls that they were disbelievers.\n");
printf("8:(38):Allah says to them that 'Join the groups of Jinn and humans who have entered the Fire before you.' When a group enters, it curses the other until when they all have entered it; so, the latter will say regarding the former, 'O our Lord, they are those who led us astray; give them therefore double the punishment of the Fire.' He will say, 'For all is double, but you know not.\n");
printf("8:(39):And the former will say to the latter, 'So, you too were no better than us; therefore, taste the punishment for what you have done.\n");
printf("8:(40):Those who belied Our verses and were arrogant against them, the gates of the heavens will not be opened for them nor will they enter Paradise until a camel goes through the eye of a needle (which will not happen); and this is how We recompense the culprits.\n");
printf("8:(41):Only Fire is the bed for them, and only Fire is the covering for them; and this is how We recompense the unjust.\n");
printf("8:(42):And those who believed and performed good deeds according to their power, We do not burden any one beyond their strength; they are the people of Paradise, wherein they will abide forever.\n");
printf("8:(43):And We have removed malice from their chests, rivers will flow beneath them, and they will say, 'All praise is due to Allah Who guided us to this, and we would not have attained the right path if Allah had not guided us. Indeed, the Messengers of our Lord brought the truth.' And it was proclaimed (to them) that 'You have received this Paradise as inheritance; the reward for your (good) deeds.\n");
printf("8:(44):And the people of Paradise called out to the people of Hell; that 'We have definitely received what our Lord had truly promised us, so, have you also received what your Lord had truly promised you?' They said, 'Yes.' And an announcer between them proclaimed that 'The curse of Allah is upon the unjust.\n");
printf("8:(45):(They are) those who prevent (people) from the path of Allah, and wish to distort it and disbelieve in the Hereafter.\n");
printf("8:(46):And between Paradise and Hell is a veil, and on the A'raaf (height) will be some men who will recognise both groups by their foreheads, and they will call to the people of Paradise; that 'Peace be upon you.' They (the people on A'raaf) have not entered Paradise (yet) and they yearn for it.\n");
printf("8:(47):And when their eyes will turn towards the people of Hell, they will say, 'O our Lord, do not include us with the unjust.\n");
printf("8:(48):And the men on the A'raaf (height) will call to some men (from Hell) whom they recognise by their foreheads, they will say, 'How did your mob and that arrogance which you used to display benefit you?\n");
printf("8:(49):The people of A'raaf will say indicating towards poor Muslims) 'Are these the people regarding whom you (O disbelievers) used to swear oaths that Allah would not have mercy upon them at all? (Whereas) it has been said to them, “Enter Paradise; there is no fear for you nor any grief.\n");
printf("8:(50):And the people of Hell will call upon the people of Paradise; that 'Provide us some benefit from your water or from that food which Allah has provided you.' They will say, 'Indeed, Allah has made both unlawful for the disbelievers.\n");
printf("8:(51):Those who made their religion play and amusement, and whom the worldly life has deceived; so, this Day We will leave them (in punishment) just like they had abandoned the concept of meeting this Day, and just like they used to deny Our verses.\n");
printf("8:(52):And We indeed brought to them a Book (i.e. the Qur'aan), which We detailed with great knowledge; guidance and mercy for the believers.\n");
printf("8:(53):What are they waiting for except for the outcome declared by that Book to appear? The Day when the declared result of that (Book) will occur. Those (i.e. the disbelievers) who had previously forgotten it will call out; that 'Indeed, the Messengers of our Lord brought the truth; so, do we have any intercessors who may intercede on our behalf? Or could we be sent back; that we may do deeds contrary to what we have done previously?' They have indeed put their souls at loss and have lost those (friends) who used to entice them with fabrication.\n");
printf("8:(54):Indeed, your Lord is Allah Who created the heavens and the earth in six days, then (after creating the Throne), He established His Dominance upon the Throne. He covers the night and the day with each other; that (one) comes swiftly following it (i.e. the other), and made the sun and the moon and the stars all subservient to His command. Pay heed! Only in His Hand (of power) is to create and to command; Most Auspicious is Allah; the Lord of all the worlds.\n");
printf("8:(55):Supplicate to your Lord in humility and softly; indeed, He does not love those who exceed the limit.\n");
printf("8:(56):And do not spread turmoil on the earth after it has been set right, and supplicate to Him; fearing and longing; indeed, the Mercy of Allah is close to the righteous.\n");
printf("8:(57):And it is He Who sends the winds; ahead of His mercy (i.e. rain) giving glad tidings, until when they come bearing heavy clouds. We drove it towards any dead town, then sent down water therewith, then produced fruits of various kinds therewith; this is how We will bring forth the dead; perhaps you accept advice.\n");
printf("8:(58):And from the fertile land comes forth its vegetation by the command of Allah, and from the infertile (land) nothing comes forth except a little with difficulty; this is how We explain the verses in different ways for those who are grateful.\n");
printf("8:(59):Indeed, We sent Nooh to his nation; so, he said, 'O my people! Worship Allah, you do not have any god except Him. Indeed, I fear for you the punishment of the Great Day (of Resurrection).\n");
printf("8:(60):The leaders of his people said, 'Indeed, we see you in open error.\n");
printf("8:(61):He said, 'O my people! There is no misguidance in me; I am in fact a Messenger of the Lord of all the worlds.\n");
printf("8:(62):(I am) conveying to you the messages of my Lord and wishing good for you, and I possess that knowledge from Allah which you possess not.\n");
printf("8:(63):And were you surprised by this; that advice came to you from your Lord through a man amongst you, so that he may warn you and that you may fear, and there may be (His) Mercy upon you?\n");
printf("8:(64):They therefore belied him; so, We rescued him and those with him in the Ark, and We drowned those who belied Our verses; indeed, that was a blind group (unable to see the truth)\n");
printf("8:(65):And (We) sent Hood to the people of 'Aad from their own community. He said, 'O my people! Worship Allah; you do not have any god except Him. So, do you not fear?\n");
printf("8:(66):The (disbelieving) leaders of his nation said, 'Indeed, we consider you foolish, and indeed, we think you are amongst the liars.\n");
printf("8:(67):He said, 'O my people! What have I got to do with foolishness? I am indeed a Messenger of the Lord of all the worlds.\n");
printf("8:(68):I convey to you the messages of my Lord and I am your trustworthy well-wisher.\n");
printf("8:(69):And were you surprised by this; that advice came to you from your Lord through a man amongst you, so that he may warn you? Remember when He made you the successors of the people of Nooh and increased the dimensions of your bodies (in height, size and strength), remember therefore the favours of Allah; that you may attain good.\n");
printf("8:(70):They said, 'Have you come to us in order that we worship only one Allah, and abandon those whom our ancestors worshipped? So, bring upon us what you promise us (i.e. punishment), if (you) are truthful.\n");
printf("8:(71):He said, 'Indeed, the punishment and the wrath of your Lord have fallen upon you. Are you disputing with me regarding only the names which you and your ancestors have kept? Allah has not sent down any authority concerning them; therefore, wait; I too await with you.\n");
printf("8:(72):We henceforth rescued him and those with him by showing great mercy from Us. And those who used to belie Our verses; We cut off their root, and they were not believers.\n");
printf("8:(73):And We sent Saalih to the (tribe of) Thamood from their own community. He said, 'O my people! Worship Allah; you do not have any god except Him. Indeed, clear proof has come to you from your Lord; this is Allah's she-camel; a sign for you, leave her free therefore to graze on Allah's earth, and do not touch her with evil (intent); that a painful punishment will overtake you.\n");
printf("8:(74):And remember when He made you successors of 'Aad and gave you a region in the earth; that you build palaces in the soft land and carve houses in the mountains. So, remember the Favours of Allah and do not roam around the earth spreading turmoil.\n");
printf("8:(75):The arrogant ones of his people said to the weak Muslims, 'Do you know that Saalih is (really) a Messenger of his Lord?' They said, 'We believe in whatever he has been sent with.\n");
printf("8:(76):The arrogant ones said, 'We deny whom you believe in.\n");
printf("8:(77):So, they cut the veins of the lower portion of the legs of the she-camel, and rebelled against the command of their Lord, and said, 'O Saalih! Bring upon us (the punishment) of which you are promising, if you are a Messenger.\n");
printf("8:(78):So, the earthquake seized them; therefore, in the morning they remained lying upside-down (dead) in their homes.\n");
printf("8:(79):Saalih therefore turned his face away from them and said, 'O my people! Indeed, I did deliver my Lord's message to you and wished you well, but you do not like the well-wishers.\n");
printf("8:(80):And (We) sent Loot; when he said to his people, 'Do you commit such shameful (acts) which no one in the world has ever committed before?\n");
printf("8:(81):'You lustfully approach men; leaving women. Rather, you have transgressed the limits.\n");
printf("8:(82):And his people had no answer except saying this; that 'Banish them (i.e. Loot and his followers) from your town; these people aspire to be pure.\n");
printf("8:(83):So, We rescued him and his family, except his (disbelieving) wife; she became of those who remained behind.\n");
printf("8:(84):And We showered upon them a rain (of stones); therefore, see what was the outcome of the criminals.\n");
printf("8:(85):And to Madyan, We sent Shu'ayb from their community. He said, 'O my people! Worship Allah; you do not have any god except Him. Indeed, a clear proof has come to you from your Lord; measure and weigh therefore in full, and do not short-change people and do not spread turmoil on the earth after it has been put in order; this is for your own good, if you believe.\n");
printf("8:(86):And do not be seated on every path in order to scare the travellers, and to prevent from Allah's Path those who believe in Him, and wishing to distort it (i.e. the Path of Allah). And remember when you were a few; He increased you (in number), and see what is the outcome of the mischief-makers.\n");
printf("8:(87):'And if a group amongst you believed in what I have been sent with, and another group did not believe; remain therefore waiting until Allah judges between us; and the judgement of Allah is the best.\n");
printf("8:(88):\n");







}





